projectName:
    - 
        name: "Baihe"
        localtion: "~/BaiheOnline"
        command: "bundle exec fastlane"
        exprotMode: 
            - "AdHoc"
            - "Enterprise"
            - "Appstore"
        version: 
            - 10_18_0: "branch_10_18_0"
            - 10_19_0: "branch_10_19_0"
    - 
        name: "Baihe"
        localtion: "~/Jiayuan"
        command: "bundle exec fastlane"
        exprotMode: 
            - "AdHoc"
            - "Enterprise"
            - "Appstore"
        version: 
            - 10_18_0: "branch_10_18_0"
            - 10_19_0: "branch_10_19_0"
    - 
        name: "Baihe"
        localtion: "~/JiaYuanA"
        command: "bundle exec fastlane"
        exprotMode: 
            - "AdHoc"
            - "Enterprise"
            - "Appstore"
        version: 
            - 10_18_0: "branch_10_18_0"
            - 10_19_0: "branch_10_19_0"
